version: '3.7'

services:
  jupyter:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_notebooks:/home/jovyan/work
      - ./scripts:/home/jovyan/scripts
    environment:

      - SPARK_HOME=/opt/spark
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: bigdata2023
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  spark-master:
    image: bitnami/spark:3.4
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_HOME=/opt/spark

volumes:
  pg_data:
  mongo_data:
